### PR TITLE
Sending Content-Length header.

### PR DESCRIPTION
**Pull request by a2ron**
Using the video information, informing about duration of the video to allow jumping around the audio stream in browsers.

Main **server.html** with a use case example and **server.js** improved with events logging and errors handlers.

### CODE REVIEW

**Comment by fukuball** [comment]
Really need this to allow jumping around the audio stream, hope merge this pull request.

**Comment by TrimA74** [comment]
why it hasn't been merge yet ?

**Comment by SLMNBJ** [comment]
Any update?

**Comment by JamesKyburz** [comment]
Thanks for the pull request, unfortunately I won't be merging this. Aside from there being lots of changes the actual problem of partial content and a known content-length wasn't solved with the library. Piping to a file first as possible as you have shown - but that means waiting for conversion prior to streaming.

I have however exposed the video object to the stream object as in this PR did.

**Pull request closed without merging**
